### ISSUE TITLE
any plan to migrate to Open Search

### ISSUE THREAD

**Issue by theSalt** [chaoss/grimoirelab-elk#1015]
Hello

Is there a plan to migrate grimoirelab-elk to be compatible with Open Search system ?

**Comment by vchrombie** [comment]
Hi @theSalt, thanks for opening the issue.

> Is there a plan to migrate grimoirelab-elk to be compatible with Open Search system ?

OpenSearch & OpenSearch Dashboards is derived from Elasticsearch 7.10.2 & Kibana 7.10.2 versions. As of now, I think GrimoireLab supports Open Distro for Elasticsearch.
https://github.com/zhquan/grimoirelab-kidash/tree/opendistro
https://github.com/zhquan/grimoirelab-sirmordred/tree/opendistro

So, it is not so difficult to make GrimoireLab work with OpenSearch directly. I tried this a few months back and I could do it with some changes in the source code, which mainly deals with the version numbers since ELK is 7.x.x and OpenSearch is 1.x.x.
https://github.com/vchrombie/grimoirelab-elk/tree/opensearch
https://github.com/vchrombie/grimoirelab-kidash/tree/opensearch
![](https://pbs.twimg.com/media/E1sEe5dVUAI488t?format=jpg&name=large)
![](https://pbs.twimg.com/media/E1sEfKpVUAM-iVG?format=jpg&name=large)
![](https://pbs.twimg.com/media/E1sEfYQUcAARg3-?format=jpg&name=large)

We are interested to adapt OpenSearch for GrimoireLab and we have that on the roadmap. I cannot give an time estimate because we are waiting for the opensearch python libraries ([opensearch-project/opensearch-dsl-py](https://github.com/opensearch-project/opensearch-dsl-py), [opensearch-project/opensearch-py](https://github.com/opensearch-project/opensearch-py)) to become more mature. We will soon work on it and get grimoirelab compatible with opensearch.

I will leave this issue open for now.

**Comment by jjmerchante** [comment]
GrimoireLab is now compatible with OpenSearch. You can deploy it using docker-compose: https://github.com/chaoss/grimoirelab/tree/master/docker-compose#opensearch
