### ISSUE TITLE
[enriched] Meetup incremental mode doesn't work if execution fails

### ISSUE THREAD

**Issue by alpgarcia** [chaoss/grimoirelab-elk#322]
The way it seems it works is:

1. Retrieve all meetups.
2. Write the corresponding enriched items.
3. Extract comments and rsvps.
4. Write comments and rsvps.

Then, if for some reason the execution fails before 4, we won't have most of the enriched items, but we will have all meetups stored in the enriched index. This means that max(metadata__timestamp), when executing in incremental mode again, will be the timestamp of the most recent meetup and we won't retrieve anything else, loosing comments and rsvps.

So, this implementation is not robust against failures and all meetup indices could miss items if enrichment failed at some point.

https://github.com/chaoss/grimoirelab-elk/blob/568f889d04fe3174c48e4f13f1f09eabd8fb0c34/grimoire_elk/enriched/meetup.py#L369

**Comment by valeriocos** [comment]
I don't think there is much to do. If the execution fails, the enriched index should be recreated from scratch (which is not a problem since we have the raw data).

@acs I would close this issue, if you don't have a better idea/solution.

**Comment by acs** [comment]
> @acs I would close this issue, if you don't have a better idea/solution.

No, closing this issue.

**Comment by sduenas** [comment]
This is a bug and it shouldn't be closed this way. I don't see a valid solution to regenerate everything from scratch. That behaviour is obscure. Anyone running it would expect this will working without regenerating the indexes. There must be a better way.

Keep this open until we find a solution. At least we will remember the bug still exist. Otherwise, it would be impossible to know it. Closing the ticket suggest the bug is fixed.

**Comment by valeriocos** [comment]
Fixed with #488
