### ISSUE TITLE
Typo in JIRA csv schema

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#361]
There is a field named: `isssue_type` (with 3 `s`'s)

I think it should be `issue_type`

**Comment by alpgarcia** [comment]
The problem comes from source code:
https://github.com/chaoss/grimoirelab-elk/blob/13b6d2e5344eb306074a71fd6aa33b963f53a9c0/grimoire_elk/enriched/jira.py#L193

This CSV was created from code and not the other way around...

And panel is also affected :woman_facepalming: : 
https://github.com/chaoss/grimoirelab-sigils/blob/477623d053cac86d47e0dc23f2734d4a8a89ac4e/json/jira.json#L23

Thansk @jsmanrique!

**Comment by valeriocos** [comment]
@alpgarcia next time consider to submit a PR, thanks!
