### ISSUE TITLE
[github enrich] How should we get the comments on Pull requests?

### ISSUE THREAD

**Issue by aswanipranjal** [chaoss/grimoirelab-elk#405]
Currently, when we fetch the data from github for only **Pull Requests** using the `--category pull_request` flag, we do not fetch the comments on the pull requests, just the number of comments. We get the review comments but not the normal comments.

We need to get the comments on PRs to calculate some of the metrics under [GMD code development](https://github.com/chaoss/wg-gmd/blob/master/2_Growth-Maturity-Decline.md#code-development) metrics. 

- One way for us to do this is to merge the data that is in the already enriched github data (issues and prs both) which contains the comments on the pull requests and add use those comments to calculate the metrics.
- second would be to add the functionality to **fetch the comments data** in perceval when we fetch the `pull_request` data.

**Comment by valeriocos** [comment]
I would vote for the first option. If we add issue comments to pull request data, we may end up issuing the same requests to the API (if we always need to fetch issue and pr data), and so we consume the token faster. 
What are your thoughts @aswanipranjal , @jgbarah , @acs , @sduenas ?

**Comment by valeriocos** [comment]
@aswanipranjal , having pull request and issue data in two different indexes is ok for you, or do you see some problems to calculate the metrics in this way?
Consider that even if the comments are in the same index, they are probably going to be stored in different attributes because the GitHub API does not allow to retrieve all kinds of comments all together: 
- https://developer.github.com/v3/issues/comments/#list-comments-on-an-issue 
- https://developer.github.com/v3/pulls/comments/#list-comments-on-a-pull-request

Another question is, do you need also comments on commits, currently Perceval doesn't fetch this data from GitHub (https://developer.github.com/v3/repos/comments/#list-commit-comments-for-a-repository)

**Comment by aswanipranjal** [comment]
> having pull request and issue data in two different indexes is ok for you, or do you see some problems to calculate the metrics in this way?

Depends. @jgbarah suggested that all the data related to PRs should stay in the PRs index. If we go with the first approach, then some of the PR related metrics will be calculated from the issues+pr index.

For example, for PRs only, the Metric [Maintainer Response to Merge Request Duration
](https://github.com/chaoss/wg-gmd/blob/master/activity-metrics/maintainer-response-to-merge-request-duration.md) will have to be calculated by taking into account both the indices(pull_requests only and issues+prs) and then taking the minimum of the first_response/attention_duration from both of the indices. It is not tough to do, so maybe we don't really need to fetch the comments data for pull_requests separately. 

It's just that I agree with Jesus that the data for issues and prs should be kept in separate indices. 
Jesus also suggested that we can probably combine both the indices using Elasticsearch Aliases. 

This is the first time that I am reading about commit comments, thanks! Will they be some sort of review to the code? I can't figure out if we can put them in some already available metric or not.

**Comment by jgbarah** [comment]
Let's clarify a bit, because I'm not sure we're all in the same page here.

The assumption is that we will have two raw (Perceval) indexes: 

* `github`, the current GitHub index, from the GitHub issues API.
* `githubpr`, the new GitHun PR index, from the GutHub Pull Requests API.

Now, with those, we would be producing a *new* enriched index, `githubpr`, with all the data needed to deal with PRs. That data would come from the two previous raw indexes, and yes, it may contain duplicated data with the current `github` enriched index.

I think at some point we would do the same with a new `githubissues` index, which will carry data only on issues, deprecating the current `github` enriched index.

@valeriocos @sduenas @acs is that ok with you?

**Comment by aswanipranjal** [comment]
closed by #419
