### ISSUE TITLE
Time_to_first_attention field missed in github_issues.csv and in github_issues index pattern

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#435]
Playing with CHAOSS GitHub Issues data, I've discovered that there is a field named `time_to_first_attention`:
https://chaoss.biterg.io/goto/7157ddf91358b1dd631b82152d6d85b3

That's great because I can chart the average [Issue Response Rate](https://github.com/chaoss/wg-gmd/blob/master/activity-metrics/first-response-to-issue-duration.md) metric:
![time_to_1st_attention_chart](https://user-images.githubusercontent.com/1178305/45215487-da7c7800-b29d-11e8-9c47-47fc60ba6ba4.jpg)

But, it doesn't appear in [gihub_issues.csv schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github_issues.csv), and neither in the `github_issues` index pattern.

Is that an issue in the `.csv` file? Something specific for CHAOSS github issues data?

**Comment by jsmanrique** [comment]
Another issue related: the field is not set as `number` so, it can't be used in charts where _numbers_ are required/expected (like gauges).

**Comment by filmaj** [comment]
I have the same issue - on my grimoirelab instance, the field shows up with a '?' as type.

<img width="915" alt="screen shot 2018-11-07 at 4 03 05 pm" src="https://user-images.githubusercontent.com/52645/48163925-a8d85b00-e2a6-11e8-8357-bd9d7c0de6a3.png">

Maybe because, as can be seen in my screenshot, some of the values in this field are empty? That seems to get set in this relevant PR: https://github.com/chaoss/grimoirelab-elk/pull/383/files#diff-76f2d3078f9b128e4eda9cccfba8fe20R265

@jsmanrique how did you get that chart that you screenshotted?

**Comment by filmaj** [comment]
I see, I can recreate your chart @jsmanrique via the Edit button (top-right) -> Timelion. Cool, good to know!

Worth mentioning that the Timelion autocomplete, when you're writing up the query, won't show the `time_to_first_attention` field, probably because it cannot infer that the type of the field is numerical.

**Comment by jsmanrique** [comment]
Yes, @filmaj, Timelion is your friend here. The autocomplete doesn't work because the lack of field type ..
