### ISSUE TITLE
Google maps lookup needs an API key

### ISSUE THREAD

**Issue by markwalkom** [chaoss/grimoirelab-elk#461]
This may be in the wrong repo sorry, I didn't know which part of the stack did the lookup but I am guessing here based on the error.

I noticed this in my logs;

```
2018-10-18 02:54:56,303 - urllib3.connectionpool - DEBUG - https://maps.googleapis.com:443 "GET /maps/api/geocode/json?address=Wellington%2C+NZ&sensor=false HTTP/1.1" 200 None
2018-10-18 02:54:56,305 - grimoire_elk.enriched.github - DEBUG - Using Maps API to find Wellington, NZ
2018-10-18 02:54:56,306 - grimoire_elk.enriched.github - DEBUG - Can't find geocode for Wellington, NZ
```

If you visit `https://maps.googleapis.com/maps/api/geocode/json?address=Wellington%2C+NZ&sensor=false` you get this response;
```
{
   "error_message" : "Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account",
   "results" : [],
   "status" : "OVER_QUERY_LIMIT"
}
```

**Comment by jgbarah** [comment]
Maybe this is a recent change in Google Maps policy? In any case, maybe we should switch to [Nominatim](https://nominatim.openstreetmap.org/), maybe in addition to still supporting Google Maps, adding options for providing a key.

**Comment by mrhillsman** [comment]
Yes, not sure how recent the change was but I have been seeing this error for some time in the logs and just got around to investigating and was about to report issue but see @markwalkom already did so +1 from me. It will also be worth mentioning or reviewing - https://operations.osmfoundation.org/policies/nominatim/ - if Nominatim is decided as a solution going forward. In particular the one request per second seems to be something that would be implemented at a minimum.

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-elk/commit/55af685054f1036cee6611557cf2a557487861d1. The geolocation information relies on [geopy](https://github.com/chaoss/grimoirelab-elk/blob/master/setup.py#L87), which leverages on Nominatim data.

Geolocation data can be added via the study `enrich_geolocation`. This study includes geo points information (latitude and longitude) based on the value of the `location_field`. The coordinates
are retrieved using Nominatim through the geopy package, and saved in the `geolocation_field`.

All locations included in the `location_field` are retrieved from the enriched index. For each location, the geo points are retrieved and saved to the `geolocation_field`. In case the geo points are not retrieved, the location is ignored.

The example below shows how to activate the study by modifying the setup.cfg. The study `enrich_geolocation:user` retrieves location data from `user_location` and stores the geo points to `user_geolocation`. In a similar manner, `enrich_geolocation:assignee` takes the data from
`assignee_location` and stores the geo points to `assignee_geolocation`.

```
[github]
raw_index = github_issues_chaoss
enriched_index = github_issues_chaoss_enriched
api-token = ...
sleep-for-rate = true
...
studies = [enrich_geolocation:user, enrich_geolocation:assignee]

[enrich_geolocation:user]
location_field = user_location
geolocation_field = user_geolocation

[enrich_geolocation:assignee]
location_field = assignee_location
geolocation_field = assignee_geolocation
```
