### ISSUE TITLE
Adding page ancestors to confluence backend

### ISSUE THREAD

**Issue by maoo** [chaoss/grimoirelab-elk#571]
In order to enrich page ancestors for Confluence documents being indexed (see  https://github.com/chaoss/grimoirelab-perceval/pull/487) the `get_rich_item` function must be extended with to copy the `ancestors` fields.

Please note that each ancestor will need to be prefixed with the Confluence server URL .

/CC @valeriocos

**Comment by maoo** [comment]
@valeriocos , is there any way I can help? Unfortunately I can't find any dev documentation in this project, so I'm not sure how to test my changes.

**Comment by sduenas** [comment]
@maoo I'm not totally sure but I think the place to include ancestors information is: [Confluence enricher](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/confluence.py#L97). You should copy the fields there in the way you think it will be useful.

You will also have to update [Confluence enriched mapping](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/confluence.csv) with the fields you are going to include and their type in ElasticSearch.

**Comment by maoo** [comment]
Thanks @sduenas !

I looked at the enricher, but I can't see any dev docs that explain how to run the tests (or other dev-related directions).

I will work on a PR and submit it here, let's take it from there. TY!

**Comment by valeriocos** [comment]
@maoo sorry for the late reply.

You can start by looking at the folder [tests](https://github.com/chaoss/grimoirelab-elk/tree/master/tests). In order to run the tests locally, you need to change the [tests.conf](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/tests.conf) with the URL of your ElasticSearch.

Then, you can focus on the tests just for the confluence data, and in particular the method [test_raw_to_enrich](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/test_confluence.py#L52), which checks that there is no data loss between raw and enrich data.

In your specific case, you have to modify the [confluence data](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/data/confluence.json), which is basically a set of JSONs obtained with Perceval. There, you can either add a couple of items which include the new ancestor data or modify some existing items. Then, in the method `test_raw_to_enrich`, you should check that the ancestor data is properly set. You can rely on code written for other ELK connectors (e.g., [slack](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/test_slack.py#L59)).

The ancestor data must be set in the method [get_rich_item](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/confluence.py#L97). In a nutshell, that method is executed for each item obtained from the raw data (e.g., Perceval), thus you have just to enter in `item`, process the ancestor data (something similar you did in Perceval, when you wanted to collect a part of the URL, if I recall correctly), and finally copy the processed data in a new field within `eitem` (i.e., the enriched item).

For documentation purposes, the new field should be added to the confluence [schema](https://github.com/chaoss/grimoirelab-elk/blob/master/schema/confluence.csv).

PS To make the tests work for ELK, you should execute once the script [test_projects.sql](https://github.com/chaoss/grimoirelab-elk/blob/master/tests/test_projects.sql) which creates and populates a MySQL db with some test data. It is not needed for the method `test_raw_to_enrich`, but you need it to make the other tests pass locally. Please have a look to the mysql instructions in the [travis.yml](https://github.com/chaoss/grimoirelab-elk/blob/master/.travis.yml#L32)
