### ISSUE TITLE
Strange support for custom fields in meta fields of projects.json

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#678]
I have a projects.json file that include some custom fields inside the `meta` field like:
```
"meta": {
    "title": "Awesome Project",
    "type": "Software"
},
```

In the data discovery tab I see expected `cm_title` and `cm_type` fields with the right data. But `cm_type` cannot be visualized, because it's not in the index pattern. `cm_title` appears as field with type `text`.

Would it be great adding any custom field in `meta` to the index pattern as `cm_{custom field name}` with type `text`.

**Comment by valeriocos** [comment]
Thank you for reporting this issue! Which index(es) are you referring to?

**Comment by valeriocos** [comment]
A workaround is to refresh the index patterns in kibana, after that you will see the missing fields.
I guess the reason of not having `cm_*` fields in the index patterns is due to the fact that they are custom fields, and thus they are not present by default.
Please @alpgarcia share your opinion, thanks

**Comment by jsmanrique** [comment]
Thank you @valeriocos, that helped. Let's wait for @alpgarcia comments

**Comment by alpgarcia** [comment]
This is probably out of the scope of Gelk. This happens when Mordred uploads standard index patterns from Sigils, so any custom field will disappear from the index pattern.

The only way to support this would be checking the `projects.json` file after uploading standard index patterns and dynamically add custom fields to Kibana index pattern object. That means uploading an index pattern to the dashboard should trigger this check to make sure custom fields are always kept.

But custom fields could be modified in the index pattern by the user, so we couldn't simply overwrite the index pattern and then add them, but we will also need to keep those changes. So, should we consider custom an index pattern having custom fields? (and thus not updating that index pattern and the affected panels anymore)

**Comment by alpgarcia** [comment]
I'm closing this issue here as Gelk can't handle this. Please open a similar one in sirmordred if needed.
