### ISSUE TITLE
[GitHub] Add study to create a "backlog" index

### ISSUE THREAD

**Issue by florentk** [chaoss/grimoirelab-elk#761]
With the current Github enriched datas, we have the backlog only from actual data, we have not the evolution.  For example we have not the evolution of the number of opened issues or the evolution of average issue resolution time. We can compute these metrics in add a new study index based on Github enirched datas.

We have implement this in a [fork of grimoirelab_elk](https://github.com/florentk/grimoirelab-elk/tree/kiwix-github-evolution-backlog) for the dev of [Kiwix metric](http://metrics.kiwix.org). Are you interested in including it as a pull request ?

**Comment by jgbarah** [comment]
Thanks a lot, this is quite interesting!

For this kind of stuff, we usually write an specific "study", which is a way of producing a "special" index (such as the one we write for the "areas of code" panels). This way, we keep the core of GrimoireELK reasonably simple, while we can have those optional studies performed as a part of what SirMordred does.

@valeriocos, @sduenas do you agree this would be the best approach to integrate this code? Do you have any pointer to studies, so that @florentk can consider if it makes sense in this case?

**Comment by alpgarcia** [comment]
Related to https://github.com/chaoss/grimoirelab-sigils/issues/410

**Comment by valeriocos** [comment]
Thank you @florentk for sharing your work. I'll have a look at it tomorrow.

**Comment by florentk** [comment]
@valeriocos Do you have look my proposition ? Can I change something to integrate my code in a branche of your repository (is the best way for us !)

**Comment by valeriocos** [comment]
Hi @florentk sorry for the late reply! Yes, I had a look to your fork and the approach looks ok!
Could you submit a PR with the study? There, we can comment on some details of the study, WDYT?

Thanks and sorry again!

**Comment by valeriocos** [comment]
This issue has been solved with:
- https://github.com/chaoss/grimoirelab-elk/pull/789
- https://github.com/chaoss/grimoirelab-elk/pull/790
- https://github.com/chaoss/grimoirelab-sirmordred/pull/408
