### ISSUE TITLE
[Zulip] Implement Zulip backend to Grimoirelab ELK

### ISSUE THREAD

**Issue by imnitishng** [chaoss/grimoirelab-elk#842]
I don't know if it's too soon for this, but Zulip backend is in progress for perceval. I'd love to add the support for data enrichment and panels once it is completed.

**Comment by valeriocos** [comment]
Hi @imnitishng, thank you for offering your help!

 Since the implementation of the Zulip backend can take some time, would you like to implement the support for the data coming from the Launchpad [backend](https://github.com/chaoss/grimoirelab-perceval/blob/master/perceval/backends/core/launchpad.py)? As you can see [here](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/raw/launchpad.py), there is a first version of the raw connector, but it should be reimplemented. On the other hand, the enricher needs to be implemented from scratch. WDYT?

**Comment by imnitishng** [comment]
Okay thanks @valeriocos, I will start working on this.

**Comment by vchrombie** [comment]
The perceval backend is implemented and being maintained in a separate repository [vchrombie/grimoirelab-perceval-zulip](https://github.com/vchrombie/grimoirelab-perceval-zulip).

There are no immediate plans on the GrimoireLab roadmap to implement the Zulip enricher, but I would be interested to collaborate if someone would like to work on it.
