### ISSUE TITLE
github2 and ocean missing csv schema

### ISSUE THREAD

**Issue by jsmanrique** [chaoss/grimoirelab-elk#850]
It seems that GrimoireLab produces indexes called `github2`, `ocean`, and `ocean_tickets` but I cannot see its schema in [existing documentation](https://github.com/chaoss/grimoirelab-elk/tree/master/schema).

Wouldn't it be nice to have the schema updated?

**Comment by valeriocos** [comment]
It seems you are using an old version of GrimoireLab.

Github2 schemas are:
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_issues.csv
- https://github.com/chaoss/grimoirelab-elk/blob/master/schema/github2_pull_requests.csv

The aliases of these indexes are listed at:
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json#L219
- https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json#L247

ocean and ocean_tickets have been replaced with all_enriched and all_enriched_tickets. 
ocean and ocean_tickets references are neither in Mordred (ref [here](https://github.com/chaoss/grimoirelab-sirmordred/blob/master/aliases.json#L247)) nor in Sigils (https://github.com/chaoss/grimoirelab-sigils/tree/master/json).

All_enriched and all_enriched_tickets don't have a CSV file. The reason is that they join all information available in the other index patterns, thus these CSV files will be extremely large. Possible solutions would be to:
- have a simplified version of these CSVs with the common fields (e.g., fields coming from SortingHat and the Projects.json), as similarly done for the affiliations.csv
- add a note here: https://github.com/chaoss/grimoirelab-elk/blob/master/schema/README.md

WDYT?

**Comment by jsmanrique** [comment]
Maybe I am, or maybe [Cauldron.io](https://cauldron.io) people are.

I'll reopen [a ticket there](https://gitlab.com/cauldronio/cauldron/-/issues/222) to clarify it.

Thank you @valeriocos !

**Comment by valeriocos** [comment]
Ok, perfect, thanks @jsmanrique !

**Comment by vchrombie** [comment]
I think we can close this issue since it looks resolved in the cauldron project too.
Feel free to open a new one.
