### ISSUE TITLE
[question] re-enriching the data

### ISSUE THREAD

**Issue by lukaszgryglicki** [chaoss/grimoirelab-elk#874]
Hi, I have a question.
- I've collected data using `p2o.py --enrich --index ... --index-enrich ... -e ... -g  --db-host ... --db-name ... --db-user ... --db-password ... datasource endpoint ...`
- Then I've changed profile data (name, emails etc) in the Sorting Hat database (not only enrollments data, but profile data too)
- Then I've run `p2o.py` in "refresh identities mode" (we're using this to regenerate profiles enrollments data when enrollments changed, including data in the past): `p2o.py --enrich --index ... --index-enrich ... -e ...--only-enrich --refresh-identities --no_incremental -g  --db-host ... --db-name ... --db-user ... --db-password ... datasource endpoint ...`, note especially `--only-enrich --refresh-identities --no_incremental` flags.

Should `p2o.py` update profile name in ElasticSearch, including past profile name in all ES documents regarding this data source endpoint? Or `--only-enrich --refresh-identities --no_incremental` is only meant to change enrollments data?

cc @valeriocos

**Comment by valeriocos** [comment]
Hi @lukaszgryglicki ,

The flag `no_incremental` doesn't seem to be needed, since it is used in the block in charge of refreshing the identities: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L497. The other flags (`only-enrich` and `refresh-identities`) are needed instead:
- https://github.com/chaoss/grimoirelab-elk/blob/master/utils/p2o.py#L74
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L495

> Should p2o.py update profile name in ElasticSearch, including past profile name in all ES documents regarding this data source endpoint? Or --only-enrich --refresh-identities --no_incremental is only meant to change enrollments data?

Enrollments data is updated, the profile name keeps the old value.
. The execution is the following:
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L510 (where `author_attr, author_values` are null)
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L195
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L807
- the identity in the doc is updated at https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L839

If we check the method [get_item_sh_fields](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L742), we can see that the profile name keeps its old value `eitem_sh[rol + "_name"] = profile.get('name', eitem_sh[rol + "_name"])` (ref: https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L772)

**Comment by lukaszgryglicki** [comment]
Thanks for the info, I'll take a look when I can (asap), I only need to tell that I also want to update past data, so I guess `no_incremental` is really needed. I'm already using `only-enrich` and `refresh-identities`, (using those 3 flags). That combination correctly refreshes enrollments data including the past. But now I'm wondering how to update profile data (in ES, including past) when data changed in SH database now.

**Comment by valeriocos** [comment]
You're welcome!

> I only need to tell that I also want to update past data, so I guess no_incremental is really needed. I'm already using only-enrich and refresh-identities, (using those 3 flags). That combination correctly refreshes enrollments data including the past. 

Ok!

> But now I'm wondering how to update profile data (in ES, including past) when data changed in SH database now.

Why you need to change this data?

**Comment by lukaszgryglicki** [comment]
Good question, this is just the functionality we want to achieve. Somebody changed data on the SH DB via UI, so we want that change to be reflected in ES.

**Comment by valeriocos** [comment]
This seems the behavior currently implemented.

Let's suppose someone updates a profile name via HatStall, the code at https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L772 (details `eitem_sh[rol + "_name"] = profile.get('name', eitem_sh[rol + "_name"])`) will give priority to what is set in the profile (`profile.get('name' ...`). If the name isn't found, the value obtained from the unique identity of SortingHat will be returned (`... eitem_sh[rol + "_name"]`)

Let me know if I'm missing something.

**Comment by lukaszgryglicki** [comment]
We're updating the SortingHat database via our own API, so SH DB is updated - this is not a problem. The problem is how to call `p2o.py` command to update data in ES, including past data (exactly as it does for enrollments that when they change on the SH DB when called with `--only-enrich --refresh-identities --no_incremental` flags)

**Comment by valeriocos** [comment]
I understand that if this code https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L770-L782 is removed, the profile data will be updated like the enrollments.

**Comment by lukaszgryglicki** [comment]
That would make a simple patch or maybe worth implementing command line flag to support that mode of operation?

**Comment by valeriocos** [comment]
That code cannot be removed from the ELK repo, because it would change the current behavior. 

If you want to have this feature in the ELK repo, the command line flag could be an option. However, the new param will affect the definition of different methods/functions (not sure if the list below is complete):
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L409
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/elk.py#L195
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L807
- https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L742

I guess there shouldn't be any problem if this new param is:
- added at the end of the methdos/functions above
- defined as optional and initialized with a default value aligned with the current behavior

Assuming that this new param (e.g., `keep_profile_info`) is True by default and propagated to `get_item_sh_fields`, a possible solution could be changing the condition [here](https://github.com/chaoss/grimoirelab-elk/blob/master/grimoire_elk/enriched/enrich.py#L770) `if profile:` to `if profile and keep_profile_info:`. Thus, if `keep_profile_info` is set to False the code under this condition won't be executed

**Comment by lukaszgryglicki** [comment]
Yeah, I was thinking about leaving the current behaviour as default and adding a parameter/flag. Will discuss that with my team and eventually create a PR that adds this functionality.
Thanks for the help!

**Comment by valeriocos** [comment]
Ok, perfect! you're welcome!

**Comment by lukaszgryglicki** [comment]
I think we can close this, thanks again for all your help!

**Comment by valeriocos** [comment]
Thank you for the info @lukaszgryglicki
