### ISSUE TITLE
Why name called "Unknown" is displayed in the dashboard ?

### ISSUE THREAD

**Issue by shikha0208** [chaoss/grimoirelab-elk#913]
Hi folks,

I am using https://github.com/chaoss/grimoirelab/blob/master/docker-compose/docker-compose.yml for the execution of dashboard.I have a issue below.If anyone knows , please have a look

Why name called unknown organisation is displayed in the image below ?Unaffiliated group , so it means it will be always this unknown?
In this image , the last tile which is "issue by organization over time" has most of them with green which is unknown org.So it is the right way?Or i should change

https://user-images.githubusercontent.com/63613092/87360165-cb397600-c569-11ea-8dd5-141618e8c826.png

Thank you .

**Comment by mafesan** [comment]
Hi @shikha0208, 

First of all, if you have different questions it would be better if you open separate issues (one per question). This way it will be easier for the rest of the community for future reference just in case anyone is having the same problem.

If you agree, let's keep this issue for solving question 1 (updating the title and description accordingly) and please open a new one for question 2. Thank you!

**Comment by shikha0208** [comment]
Hi @mafesan ,

Yes i have updated the issue and opened new issue for the 2nd question.

**Comment by mafesan** [comment]
Hi again @shikha0208, 

Thank you for separating the issues! :smile:

To give you some context, [SortingHat](https://github.com/chaoss/grimoirelab-sortinghat) is the GrimoireLab tool behind the scenes which is in charge of managing the identities information from the sources you are analyzing. 

SortingHat allows to manage affiliation information too, including the organization(s) a person/user belongs to and the date periods for each of them. The organization a user belongs to can be inferred using the email domains from every user, for instance: if we have a user which contributed to one of the sources with an email with domain `@mozilla.com`, it will be automatically affiliated to `Mozilla` organization.

This automatic affiliation works because there is an entry in SortingHat registry matching `mozilla.com` domain with `Mozilla` organization. When this automatic affiliation cannot be applied, that user will not have any affiliation information (at least for the period of time you are visualizing on the dashboard after setting a date range with the time-picker), it will appear as `Unknown` on the dashboard.

This could be happening because:
* (1) There is no email domain information for those users.
* (2) Their email domain(s) are not linked to any organization in SortingHat.
* (3) The same user can have different identities (e.g. contributions coming from different sources or accounts) and they are considered as different individuals.

About possible solutions:
* (2) can be solved by adding the corresponding entry to SortingHat.
* (3) can be solved by merging those identities under the same individual, which can be done via SortingHat too.

I hope this helps!

Best, Miguel Ángel

**Comment by shikha0208** [comment]
Hi @mafesan ,

Thank you so much for the detailed information.

Correct me , if my understanding is not right.
In SortingHat ,there are already specified domains are present ,Can i see them where are they?
So i cannot add my new xyzdomain , so that if my email i use @xzydomain ,it should work.

How can i add a different entry ?

**Comment by mafesan** [comment]
Hi @shikha0208, 

> In SortingHat ,there are already specified domains are present ,Can i see them where are they?

You are right. By default, SortingHat is importing the list of organizations and domains [from this file](https://github.com/chaoss/grimoirelab/blob/master/default-grimoirelab-settings/organizations.json).

> How can i add a different entry ?

You can add a new entry using [Hatstall](https://github.com/chaoss/grimoirelab-hatstall), which is a web interface to interact with SortingHat. Executing the `docker-compose` file you commented at the beginning of the issue, you can access Hatstall from  `http://127.0.0.1:8000/`. Default credentials are `admin`-`admin`, as you can check in [this README section](https://github.com/chaoss/grimoirelab/tree/master/docker-compose#getting-started-in-3-steps). 

For adding a new organization domain from Hatstall, you have to click on `Organizations` tab on the nav bar, and then:
* First, look for the organization you are interested in (you can navigate though the pages or you can use the search bar).
  * If the organization you are looking for does not appear, click on `Add` button and add the new organization first.
* Once you have located the organization, click on `edit` and then a menu will pop-up on the right. There you will be able to add new domains for that organization.

![example-add-domain](https://user-images.githubusercontent.com/9032790/87524852-ff578880-c688-11ea-8331-9e6a9062cf8d.png)

I hope it helps! 

Best, Miguel Angel

**Comment by shikha0208** [comment]
Hi @mafesan ,

Thank you for the file location  and the explanation.
Closing the issue.
