### ISSUE TITLE
Handle GitHub issue comments during enrichment phase

### ISSUE THREAD

**Issue by sduenas** [chaoss/grimoirelab-elk#98]
The latest version of GitHub backend in Perceval fetches the comments of each issue. GrimoireELK should handle these comments to enrich items with these data.

See grimoirelab/perceval#53

**Comment by acs** [comment]
We need to define howto include those comments in the enriched index. Probably we want to add a new field comments with type array and with all the comments. But I have not a clear vision on howto use that information in the panels. In a first version we can just show all the comments in a widget for and issue. If we add the comments, we can search using words ... Adding @alpgarcia to the conversation!

**Comment by alpgarcia** [comment]
Yep, at first glance the easiest way seems to be a list of text object (in order to make them searchable). 

Adding @jgbarah and @dicortazar to the loop as I want to know their opinions about including comments in the existing github enriched index or using a new one. Which use cases do you have in mind?

Do we have a comparison of index sizes with comments and without?

**Comment by jgbarah** [comment]
I think that instead of thinking about how to visualize comments (or maybe in addition to that) we should think about what we intend to visualize.

For a complete visualization, I think we need what @dicortazar calls "index events", with each "event" (in this case, a comment, or a change to a ticket) as an item in the index.

For a summary visualization, I think that counts of items per ticket, counts of people sending comments per message, and maybe keywords, would be convenient. I'm not sure about having the whole text in the kind of indexes we have now...

**Comment by robinmuilwijk** [comment]
What would be interesting to see, is how many unique people comment, and how many comments their are on an issue. This is an indicator for community engagement for GitHub commits.

I would be interested in presenting this as total number of issues, total number of comments, and unique total number of commenters. This would provide a indication on engagement overall.

**Comment by jgbarah** [comment]
@robinmuilwijk I agree with that. But very likely, it would also be convenient to know who is actually commenting, which means we should also keep track of those names (and maybe dates). This would lead to an entry per comment...

**Comment by valeriocos** [comment]
...and finally fixed: https://github.com/chaoss/grimoirelab-elk/pull/737
